[package]
name = "blurhash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-srgb8 = "1.0"
image = "0.24"
thiserror = "1.0"
